
import type { DataItem, Column } from './types';

export const INITIAL_COLUMNS: Column[] = [
  { key: 'name', label: 'Name', visible: true, sortable: true },
  { key: 'email', label: 'Email', visible: true, sortable: true },
  { key: 'role', label: 'Role', visible: true, sortable: true },
  { key: 'status', label: 'Status', visible: true, sortable: true },
  { key: 'department', label: 'Dept', visible: true, sortable: true },
  { key: 'location', label: 'Location', visible: true, sortable: true },
  { key: 'phone', label: 'Phone', visible: false, sortable: true },
  { key: 'progress', label: 'Progress', visible: true, sortable: true },
  { key: 'lastLogin', label: 'Last Login', visible: true, sortable: true },
  { key: 'createdAt', label: 'Created At', visible: false, sortable: true },
  { key: 'actions', label: 'Actions', visible: true, sortable: false },
];

export const MOCK_DATA: DataItem[] = [
  {
    id: '1',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2024-05-12 14:30',
    location: 'San Francisco, CA',
    department: 'Engineering',
    phone: '+1 555-0101',
    createdAt: '2023-01-15',
    progress: 85,
  },
  {
    id: '2',
    name: 'Sarah Chen',
    email: 'sarah.c@example.com',
    role: 'Editor',
    status: 'Active',
    lastLogin: '2024-05-13 09:15',
    location: 'Seattle, WA',
    department: 'Product',
    phone: '+1 555-0102',
    createdAt: '2023-02-20',
    progress: 92,
  },
  {
    id: '3',
    name: 'Marcus Thorne',
    email: 'mthorne@example.com',
    role: 'Viewer',
    status: 'Inactive',
    lastLogin: '2024-04-28 11:00',
    location: 'Austin, TX',
    department: 'Sales',
    phone: '+1 555-0103',
    createdAt: '2023-03-05',
    progress: 45,
  },
  {
    id: '4',
    name: 'Elena Rodriguez',
    email: 'elena.r@example.com',
    role: 'Manager',
    status: 'Pending',
    lastLogin: '2024-05-10 16:45',
    location: 'New York, NY',
    department: 'Marketing',
    phone: '+1 555-0104',
    createdAt: '2023-05-12',
    progress: 10,
  },
  {
    id: '5',
    name: 'Julian Vane',
    email: 'jvane@example.com',
    role: 'Editor',
    status: 'Active',
    lastLogin: '2024-05-13 10:00',
    location: 'Chicago, IL',
    department: 'Engineering',
    phone: '+1 555-0105',
    createdAt: '2023-06-01',
    progress: 78,
  },
  {
    id: '6',
    name: 'Lila Grace',
    email: 'lila.g@example.com',
    role: 'Viewer',
    status: 'Suspended',
    lastLogin: '2024-03-15 08:30',
    location: 'Denver, CO',
    department: 'HR',
    phone: '+1 555-0106',
    createdAt: '2023-07-22',
    progress: 0,
  },
  {
    id: '7',
    name: 'Victor Kael',
    email: 'vkael@example.com',
    role: 'Manager',
    status: 'Active',
    lastLogin: '2024-05-12 12:00',
    location: 'Miami, FL',
    department: 'Sales',
    phone: '+1 555-0107',
    createdAt: '2023-08-14',
    progress: 100,
  },
  {
    id: '8',
    name: 'Fiona Wu',
    email: 'fiona@example.com',
    role: 'Admin',
    status: 'Active',
    lastLogin: '2024-05-13 11:20',
    location: 'Portland, OR',
    department: 'Product',
    phone: '+1 555-0108',
    createdAt: '2023-09-05',
    progress: 64,
  },
  {
    id: '9',
    name: 'Derek Jones',
    email: 'dj@example.com',
    role: 'Viewer',
    status: 'Inactive',
    lastLogin: '2024-04-10 15:45',
    location: 'Atlanta, GA',
    department: 'Engineering',
    phone: '+1 555-0109',
    createdAt: '2023-10-18',
    progress: 30,
  },
  {
    id: '10',
    name: 'Maya Sun',
    email: 'maya@example.com',
    role: 'Editor',
    status: 'Pending',
    lastLogin: '2024-05-01 10:10',
    location: 'Boston, MA',
    department: 'Marketing',
    phone: '+1 555-0110',
    createdAt: '2023-11-20',
    progress: 15,
  }
];
