package com.github.project_fredica.api.routes

import com.github.project_fredica.api.FredicaApi


// AI建议：按字母序排序
fun FredicaApi.Route.Companion.getCommonRoutes() = listOf(
    BilibiliFavoriteGetPageRoute,
    BilibiliFavoriteGetVideoListRoute,
    BilibiliVideoAiConclusionRoute,
    BilibiliVideoDownloadRoute,
    BilibiliVideoGetPagesRoute,
    BilibiliVideoSubtitleBodyRoute,
    BilibiliVideoSubtitleRoute,
    FasterWhisperConfigInfoRoute,
    ImageProxyRoute,
    LlmModelAvailabilityRoute,
    LlmModelListRoute,
    LlmModelProbeRoute,
    MaterialActiveTasksRoute,
    MaterialCategoryCreateRoute,
    MaterialCategoryDeleteRoute,
    MaterialCategoryListRoute,
    MaterialDeleteRoute,
    MaterialDownloadStatusRoute,
    MaterialImportRoute,
    MaterialGetRoute,
    MaterialListRoute,
    MaterialSetCategoriesRoute,
    MaterialSubtitleContentRoute,
    MaterialSubtitleListRoute,
    MaterialTaskListRoute,
    MaterialVideoCheckRoute,
    MaterialVideoTranscodeMp4Route,
    MaterialWorkflowRoute,
    MaterialWorkflowStatusRoute,
    NetworkTestRoute,
    PromptTemplateDeleteRoute,
    PromptTemplateGetRoute,
    PromptTemplateListRoute,
    PromptTemplateSaveRoute,
    RestartTaskLogListRoute,
    RestartTaskLogUpdateDispositionRoute,
    TaskCancelRoute,
    TaskPauseRoute,
    TaskResumeRoute,
    WebenConceptBatchImportRoute,
    WebenConceptGetRoute,
    WebenConceptListRoute,
    WebenConceptUpdateRoute,
    WebenFlashcardCreateRoute,
    WebenFlashcardListRoute,
    WebenFlashcardReviewRoute,
    WebenLearningPathRoute,
    WebenNoteDeleteRoute,
    WebenNoteListRoute,
    WebenNoteSaveRoute,
    WebenRelationCreateRoute,
    WebenRelationDeleteRoute,
    WebenRelationListRoute,
    WebenReviewQueueRoute,
    WebenSegmentListRoute,
    WebenSourceListRoute,
    WorkerTaskListRoute,
    WorkerTaskWfIdListRoute,
    // 注: LlmProxyChatRoute 使用 SSE 格式传递，因此并不在此处列入。
)
